# Generated by Django 6.0.1 on 2026-04-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_xp",
            field=models.PositiveIntegerField(default=0, help_text="Lifetime XP earned across all sessions"),
        ),
    ]
