# Generated by Django 6.0.1 on 2026-04-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_total_xp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="peak_rating",
            field=models.PositiveIntegerField(default=1000, help_text="Highest rating ever achieved"),
        ),
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.PositiveIntegerField(default=1000, help_text="Skill rating (Elo-like), starts at 1000"),
        ),
    ]
