# Generated by Django 6.0.1 on 2026-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_peak_rating_user_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pronunciation_trials_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
