# Generated by Django 6.0.1 on 2026-05-12 12:55
# Wrapped in SeparateDatabaseAndState — tables already exist as learning_* in the DB.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clips", "0007_reel_reelline_reelview_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="CoreWord",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(db_index=True, max_length=100, unique=True)),
                    ],
                    options={
                        "db_table": "learning_coreword",
                        "ordering": ["word"],
                    },
                ),
                migrations.CreateModel(
                    name="VocabWord",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(max_length=100, unique=True)),
                        ("frequency_rank", models.PositiveIntegerField(unique=True)),
                        (
                            "tier",
                            models.IntegerField(
                                choices=[
                                    (1, "Tier 1 — Core"),
                                    (2, "Tier 2 — Common"),
                                    (3, "Tier 3 — Familiar"),
                                    (4, "Tier 4 — Advanced"),
                                    (5, "Tier 5 — Expert"),
                                ]
                            ),
                        ),
                        (
                            "pos",
                            models.CharField(
                                choices=[
                                    ("n", "Noun"),
                                    ("v", "Verb"),
                                    ("adj", "Adjective"),
                                    ("adv", "Adverb"),
                                    ("phr", "Phrase"),
                                    ("etc", "Other"),
                                ],
                                default="etc",
                                max_length=5,
                            ),
                        ),
                        ("uzbek_translation", models.CharField(max_length=200)),
                        ("uzbek_synonyms", models.CharField(blank=True, max_length=500)),
                        ("example_sentence", models.TextField(blank=True)),
                        ("gif_url", models.URLField(blank=True)),
                    ],
                    options={
                        "db_table": "learning_vocabword",
                        "ordering": ["frequency_rank"],
                    },
                ),
                migrations.CreateModel(
                    name="WordCache",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(max_length=100, unique=True)),
                        (
                            "pos",
                            models.CharField(
                                choices=[
                                    ("v", "Verb"),
                                    ("n", "Noun"),
                                    ("adj", "Adjective"),
                                    ("phr", "Phrase"),
                                    ("etc", "Other"),
                                ],
                                default="etc",
                                max_length=5,
                            ),
                        ),
                        ("definition", models.TextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "db_table": "learning_wordcache",
                    },
                ),
                migrations.CreateModel(
                    name="WordTranslation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(db_index=True, max_length=100, unique=True)),
                        ("translation", models.CharField(max_length=300)),
                        (
                            "level",
                            models.CharField(
                                choices=[
                                    ("A1", "A1"),
                                    ("A2", "A2"),
                                    ("B1", "B1"),
                                    ("B2", "B2"),
                                    ("C1", "C1"),
                                    ("C2", "C2"),
                                ],
                                default="B1",
                                max_length=2,
                            ),
                        ),
                        ("frequency", models.PositiveIntegerField(default=0)),
                    ],
                    options={
                        "db_table": "learning_wordtranslation",
                        "ordering": ["-frequency", "word"],
                    },
                ),
                migrations.CreateModel(
                    name="LineTranslation",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("translation", models.TextField()),
                        ("season", models.PositiveIntegerField(blank=True, null=True)),
                        ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                        (
                            "episode",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_translations",
                                to="clips.episode",
                            ),
                        ),
                        (
                            "source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_translations",
                                to="clips.source",
                            ),
                        ),
                        (
                            "transcript",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_translation",
                                to="clips.transcript",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_linetranslation",
                        "ordering": ["source", "season", "episode_number", "transcript__start_time"],
                    },
                ),
                migrations.CreateModel(
                    name="LineVocab",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("vocab_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                        ("english", models.CharField(max_length=200)),
                        ("translation", models.CharField(max_length=300)),
                        (
                            "kind",
                            models.CharField(
                                choices=[
                                    ("verb", "Verb"),
                                    ("noun", "Noun"),
                                    ("adj", "Adjective"),
                                    ("adv", "Adverb"),
                                    ("phrasal_verb", "Phrasal Verb"),
                                    ("phrase", "Phrase"),
                                    ("pattern", "Pattern"),
                                    ("idiom", "Idiom"),
                                ],
                                default="phrase",
                                max_length=15,
                            ),
                        ),
                        (
                            "level",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("A1", "A1"),
                                    ("A2", "A2"),
                                    ("B1", "B1"),
                                    ("B2", "B2"),
                                    ("C1", "C1"),
                                    ("C2", "C2"),
                                ],
                                default="",
                                max_length=2,
                            ),
                        ),
                        (
                            "category",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("social", "Social"),
                                    ("relationships", "Relationships"),
                                    ("emotions", "Emotions"),
                                    ("home", "Home"),
                                    ("household", "Household"),
                                    ("body", "Body"),
                                    ("food", "Food"),
                                    ("humor", "Humor"),
                                    ("entertainment", "Entertainment"),
                                    ("work", "Work"),
                                    ("personal_growth", "Personal Growth"),
                                    ("general", "General"),
                                ],
                                default="",
                                max_length=20,
                            ),
                        ),
                        ("description", models.TextField(blank=True)),
                        ("example", models.TextField(blank=True)),
                        ("pattern", models.CharField(blank=True, max_length=300)),
                        ("tavsif", models.TextField(blank=True)),
                        ("smart_mcq", models.JSONField(blank=True, default=dict)),
                        ("usage_check", models.JSONField(blank=True, default=dict)),
                        ("translated_examples", models.JSONField(blank=True, default=list)),
                        ("confusable_with", models.JSONField(blank=True, default=list)),
                        ("collocations", models.JSONField(blank=True, default=list)),
                        ("season", models.PositiveIntegerField(blank=True, null=True)),
                        ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                        (
                            "episode",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_vocab",
                                to="clips.episode",
                            ),
                        ),
                        (
                            "source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_vocab",
                                to="clips.source",
                            ),
                        ),
                        (
                            "transcript",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="line_vocab",
                                to="clips.transcript",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_linevocab",
                        "ordering": ["source", "season", "episode_number", "transcript__start_time"],
                        "unique_together": {("transcript", "english")},
                    },
                ),
                migrations.CreateModel(
                    name="SuggestedWord",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(db_index=True, max_length=100)),
                        ("definition", models.CharField(blank=True, default="", max_length=300)),
                        ("translation", models.CharField(blank=True, default="", max_length=200)),
                        (
                            "level",
                            models.CharField(
                                choices=[
                                    ("beginner", "Beginner"),
                                    ("intermediate", "Intermediate"),
                                    ("advanced", "Advanced"),
                                ],
                                default="beginner",
                                max_length=15,
                            ),
                        ),
                        ("frequency", models.PositiveIntegerField(default=0)),
                        ("usage_examples", models.JSONField(blank=True, default=list)),
                        ("grammar_note", models.CharField(blank=True, default="", max_length=300)),
                        ("sentence", models.TextField()),
                        ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                        ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                        ("season", models.PositiveIntegerField(blank=True, null=True)),
                        ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                        (
                            "episode",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="suggested_words",
                                to="clips.episode",
                            ),
                        ),
                        (
                            "source",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="suggested_words",
                                to="clips.source",
                            ),
                        ),
                        (
                            "transcript",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="suggested_words",
                                to="clips.transcript",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_suggestedword",
                        "ordering": ["source", "season", "episode_number", "start_time"],
                        "unique_together": {("transcript", "word")},
                    },
                ),
                migrations.CreateModel(
                    name="VocabMastery",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("p_known", models.FloatField(default=0.1)),
                        ("translation_score", models.FloatField(default=0)),
                        ("context_score", models.FloatField(default=0)),
                        ("production_score", models.FloatField(default=0)),
                        ("mastery_score", models.FloatField(default=0)),
                        (
                            "level",
                            models.CharField(
                                choices=[
                                    ("weak", "Weak"),
                                    ("shaky", "Shaky"),
                                    ("good", "Good"),
                                    ("strong", "Strong"),
                                    ("mastered", "Mastered"),
                                ],
                                default="weak",
                                max_length=10,
                            ),
                        ),
                        ("overall_score", models.FloatField(default=0)),
                        ("difficulty", models.FloatField(default=1000)),
                        ("streak", models.PositiveIntegerField(default=0)),
                        ("attempts", models.PositiveIntegerField(default=0)),
                        ("next_review", models.DateTimeField(default=django.utils.timezone.now)),
                        ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                        ("interval_days", models.FloatField(default=0)),
                        ("ease_factor", models.FloatField(default=2.5)),
                        ("lapses", models.PositiveIntegerField(default=0)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="vocab_masteries",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "vocab",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="masteries",
                                to="vocab.linevocab",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_vocabmastery",
                        "ordering": ["mastery_score"],
                        "unique_together": {("user", "vocab")},
                    },
                ),
                migrations.CreateModel(
                    name="WordNote",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                            ),
                        ),
                        ("word", models.CharField(max_length=100)),
                        (
                            "pos",
                            models.CharField(
                                choices=[
                                    ("v", "Verb"),
                                    ("n", "Noun"),
                                    ("adj", "Adjective"),
                                    ("phr", "Phrase"),
                                    ("etc", "Other"),
                                ],
                                default="etc",
                                max_length=5,
                            ),
                        ),
                        ("definition", models.TextField(blank=True)),
                        ("translation", models.CharField(blank=True, default="", max_length=500)),
                        (
                            "stage",
                            models.CharField(
                                choices=[("inbox", "Inbox"), ("learning", "Learning"), ("mastered", "Mastered")],
                                default="inbox",
                                max_length=20,
                            ),
                        ),
                        ("confidence", models.IntegerField(default=0)),
                        (
                            "mood",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("sarcastic", "Sarcastic"),
                                    ("angry", "Angry"),
                                    ("funny", "Funny"),
                                    ("romantic", "Romantic"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "emotion_vibe",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("nostalgic", "Nostalgic"),
                                    ("thrilling", "Thrilling"),
                                    ("inspiring", "Inspiring"),
                                    ("humorous", "Humorous"),
                                    ("tense", "Tense"),
                                    ("heartwarming", "Heartwarming"),
                                ],
                                max_length=20,
                            ),
                        ),
                        (
                            "scene_timestamp",
                            models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
                        ),
                        ("scene_frame", models.ImageField(blank=True, null=True, upload_to="scene_frames/")),
                        ("personal_note", models.TextField(blank=True)),
                        ("example_usage", models.TextField(blank=True)),
                        ("usage_examples", models.JSONField(blank=True, default=list)),
                        ("grammar_note", models.CharField(blank=True, default="", max_length=300)),
                        (
                            "context_type",
                            models.CharField(
                                blank=True,
                                choices=[
                                    ("idiom", "Idiom"),
                                    ("slang", "Slang"),
                                    ("formal", "Formal"),
                                    ("phrasal_verb", "Phrasal Verb"),
                                    ("expression", "Expression"),
                                    ("sarcasm", "Sarcasm"),
                                    ("humor", "Humor"),
                                    ("casual", "Casual"),
                                ],
                                max_length=50,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "next_review",
                            models.DateTimeField(
                                blank=True, db_index=True, default=django.utils.timezone.now, null=True
                            ),
                        ),
                        ("review_count", models.PositiveIntegerField(default=0)),
                        ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                        (
                            "quote",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="word_notes",
                                to="clips.quote",
                            ),
                        ),
                        (
                            "transcript",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="word_notes",
                                to="clips.transcript",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="word_notes",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "learning_wordnote",
                        "ordering": ["-created_at"],
                        "unique_together": {("user", "transcript", "word")},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
