# Generated by Django 6.0.1 on 2026-05-12 12:55
# Wrapped in SeparateDatabaseAndState — updates FK targets in ORM state only (no DDL).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="quizattempt",
                    name="note",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="vocab.wordnote",
                    ),
                ),
                migrations.AlterField(
                    model_name="quizattempt",
                    name="vocab",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="vocab.linevocab",
                    ),
                ),
                migrations.AlterField(
                    model_name="savedsentence",
                    name="note",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_sentences",
                        to="vocab.wordnote",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
