# Generated by Django 6.0.1 on 2026-02-13 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("season", models.PositiveIntegerField()),
                ("episode_number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("video_file", models.FileField(blank=True, null=True, upload_to="episodes/")),
                ("duration", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["season", "episode_number"],
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("start_time", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ("end_time", models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ("views", models.PositiveIntegerField(default=0)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="quote_thumbnails/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, null=True, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv_show", "TV Show")], default="movie", max_length=20
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="thumbnails/")),
                ("video_file", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("duration", models.PositiveIntegerField(blank=True, help_text="Duration in seconds", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
