# Generated by Django 6.0.1 on 2026-02-08 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("source_type", models.CharField(max_length=50)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("episode", models.IntegerField(blank=True, null=True)),
                ("year", models.IntegerField(null=True)),
                ("thumbnail", models.ImageField(upload_to="thumbnails/")),
                ("video_file", models.FileField(upload_to="videos/")),
                ("duration", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quotes", to="clips.source"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("quote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="clips.quote")),
            ],
            options={
                "unique_together": {("user", "quote")},
            },
        ),
    ]
