# Generated by Django 6.0.1 on 2026-02-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AlterField(
            model_name="source",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
