# Generated by Django 6.0.1 on 2026-02-13 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clips", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="quote",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="clips.episode",
            ),
        ),
        migrations.AddField(
            model_name="favorite",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="favorited_by", to="clips.quote"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="quotes", to="clips.source"
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="clips.source"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "quote")},
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("source", "season", "episode_number")},
        ),
    ]
