# Generated by Django 6.0.1 on 2026-02-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="transcripts", to="clips.episode"
                    ),
                ),
            ],
        ),
    ]
