# Generated by Django 6.0.1 on 2026-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0002_alter_source_thumbnail_alter_source_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_type",
            field=models.CharField(choices=[("movie", "Movie"), ("tv_show", "TV Show")], max_length=50),
        ),
    ]
