# Generated by Django 6.0.1 on 2026-02-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clips", "0003_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="clips.source",
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transcripts",
                to="clips.episode",
            ),
        ),
    ]
