# Generated by Django 6.0.1 on 2026-02-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0005_watchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to="scene_thumbnails/")),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_blocks",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scene_blocks", to="clips.source"
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
