# Generated by Django 6.0.1 on 2026-05-07 08:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clips", "0006_sceneblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Short headline (e.g. 'Joey's audition')", max_length=140)),
                ("description", models.TextField(blank=True, help_text="1-2 lines of setup shown under the reel")),
                (
                    "start_time",
                    models.FloatField(
                        help_text="Start time in source video (seconds)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "end_time",
                    models.FloatField(
                        help_text="End time in source video (seconds)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "poster_frame",
                    models.FloatField(
                        blank=True, help_text="Timestamp to snapshot for the thumbnail (default: midpoint)", null=True
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated; can be overridden",
                        null=True,
                        upload_to="reel_thumbnails/",
                    ),
                ),
                (
                    "cefr_level",
                    models.CharField(
                        choices=[
                            ("A1", "A1 — Beginner"),
                            ("A2", "A2 — Elementary"),
                            ("B1", "B1 — Intermediate"),
                            ("B2", "B2 — Upper-Intermediate"),
                            ("C1", "C1 — Advanced"),
                            ("C2", "C2 — Mastery"),
                        ],
                        default="B1",
                        help_text="Difficulty band — drives feed personalization",
                        max_length=2,
                    ),
                ),
                (
                    "comedy_score",
                    models.PositiveSmallIntegerField(default=5, help_text="1-10: how funny / re-watchable"),
                ),
                ("is_published", models.BooleanField(default=False, help_text="Show in the public Reels feed")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                (
                    "save_count",
                    models.PositiveIntegerField(default=0, help_text="Users who saved a word from this reel"),
                ),
                (
                    "shadow_count",
                    models.PositiveIntegerField(default=0, help_text="Users who shadowed at least one line"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        help_text="For TV shows: which episode this reel comes from",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reels",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reels", to="clips.source"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReelLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0, help_text="Display order within the reel")),
                ("is_shadow_target", models.BooleanField(default=False, help_text="Marked for shadowing practice")),
                (
                    "is_punchline",
                    models.BooleanField(default=False, help_text="Comedy beat — used by future highlight-reel mode"),
                ),
                (
                    "target_words",
                    models.JSONField(blank=True, default=list, help_text="List of important words this line teaches"),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="clips.reel"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_appearances",
                        to="clips.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ReelView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False, help_text="Watched ≥80% of the reel duration")),
                ("shadowed_lines", models.PositiveIntegerField(default=0)),
                ("saved_words", models.PositiveIntegerField(default=0)),
                ("liked", models.BooleanField(default=False)),
                ("bookmarked", models.BooleanField(default=False)),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_views", to="clips.reel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reel_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(fields=["is_published", "-published_at"], name="clips_reel_is_publ_f2b950_idx"),
        ),
        migrations.AddIndex(
            model_name="reel",
            index=models.Index(fields=["cefr_level", "is_published"], name="clips_reel_cefr_le_77beea_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reelline",
            unique_together={("reel", "transcript")},
        ),
        migrations.AddIndex(
            model_name="reelview",
            index=models.Index(fields=["user", "-last_seen_at"], name="clips_reelv_user_id_de3442_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reelview",
            unique_together={("user", "reel")},
        ),
    ]
