# Generated by Django 6.0.1 on 2026-02-13 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clips", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_quotes_reviewed", models.PositiveIntegerField(default=0)),
                ("total_words_noted", models.PositiveIntegerField(default=0)),
                ("total_session_minutes", models.PositiveIntegerField(default=0)),
                ("total_cloze_attempts", models.PositiveIntegerField(default=0)),
                ("total_cloze_correct", models.PositiveIntegerField(default=0)),
                ("saved_count", models.PositiveIntegerField(default=0)),
                ("learning_count", models.PositiveIntegerField(default=0)),
                ("mastered_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("quotes_reviewed", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("cloze", "Fill in the Blank"),
                            ("shadow", "Shadow Mode"),
                            ("review", "Quote Review"),
                            ("mixed", "Mixed"),
                        ],
                        default="mixed",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClozeResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_word", models.CharField(max_length=100)),
                ("user_answer", models.CharField(max_length=100)),
                ("is_correct", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cloze_results", to="clips.quote"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cloze_results",
                        to="learning.reviewsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("personal_note", models.TextField(blank=True)),
                (
                    "emotion_tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("funny", "😂 Funny"),
                            ("sad", "😢 Sad"),
                            ("angry", "😡 Angry"),
                            ("romantic", "😍 Romantic"),
                            ("confused", "🤔 Confused"),
                            ("excited", "🎉 Excited"),
                            ("frustrated", "😤 Frustrated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_favorites",
                        to="clips.quote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "quote")},
            },
        ),
        migrations.CreateModel(
            name="QuoteMastery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("saved", "📌 Saved"), ("learning", "🔄 Learning"), ("mastered", "✅ Mastered")],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                ("next_review", models.DateTimeField(blank=True, null=True)),
                ("interval_days", models.PositiveIntegerField(default=1)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="masteries", to="clips.quote"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review"],
                "unique_together": {("user", "quote")},
            },
        ),
        migrations.CreateModel(
            name="SourceProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quotes_seen", models.PositiveIntegerField(default=0)),
                ("quotes_favorited", models.PositiveIntegerField(default=0)),
                ("quotes_mastered", models.PositiveIntegerField(default=0)),
                ("last_watched", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="user_progress", to="clips.source"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "source")},
            },
        ),
        migrations.CreateModel(
            name="WordNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100)),
                ("definition", models.TextField(blank=True)),
                ("personal_note", models.TextField(blank=True)),
                ("example_usage", models.TextField(blank=True)),
                (
                    "context_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("idiom", "Idiom"),
                            ("slang", "Slang"),
                            ("formal", "Formal"),
                            ("phrasal_verb", "Phrasal Verb"),
                            ("expression", "Expression"),
                            ("sarcasm", "Sarcasm"),
                            ("humor", "Humor"),
                            ("casual", "Casual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="word_notes", to="clips.quote"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "quote", "word")},
            },
        ),
    ]
