# Generated by Django 6.0.1 on 2026-02-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=100, unique=True)),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("v", "Verb"),
                            ("n", "Noun"),
                            ("adj", "Adjective"),
                            ("phr", "Phrase"),
                            ("etc", "Other"),
                        ],
                        default="etc",
                        max_length=5,
                    ),
                ),
                ("definition", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
