# Generated by Django 6.0.1 on 2026-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_wordcache"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="pos",
            field=models.CharField(
                choices=[("v", "Verb"), ("n", "Noun"), ("adj", "Adjective"), ("phr", "Phrase"), ("etc", "Other")],
                default="etc",
                max_length=5,
            ),
        ),
    ]
