# Generated by Django 6.0.1 on 2026-02-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0003_wordnote_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="translation",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
