# Generated by Django 6.0.1 on 2026-02-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_wordnote_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="confidence",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="stage",
            field=models.CharField(
                choices=[("inbox", "Inbox"), ("learning", "Learning"), ("mastered", "Mastered")],
                default="inbox",
                max_length=20,
            ),
        ),
    ]
