# Generated by Django 6.0.1 on 2026-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0005_wordnote_confidence_wordnote_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[("sarcastic", "Sarcastic"), ("angry", "Angry"), ("funny", "Funny"), ("romantic", "Romantic")],
                max_length=20,
            ),
        ),
    ]
