# Generated by Django 6.0.1 on 2026-02-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clips", "0005_watchhistory"),
        ("learning", "0008_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wordnote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="transcript",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_notes",
                to="clips.transcript",
            ),
        ),
        migrations.AlterField(
            model_name="wordnote",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_notes",
                to="clips.quote",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wordnote",
            unique_together={("user", "transcript", "word")},
        ),
    ]
