# Generated by Django 6.0.1 on 2026-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_wordnote_transcript_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoreWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                "ordering": ["word"],
            },
        ),
    ]
