# Generated by Django 6.0.1 on 2026-02-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0010_coreword"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuggestedWord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(db_index=True, max_length=100)),
                ("sentence", models.TextField(help_text="The full subtitle line where the word appears")),
                ("start_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("end_time", models.DecimalField(decimal_places=3, max_digits=10)),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_words",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="suggested_words", to="clips.source"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_words",
                        to="clips.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "season", "episode_number", "start_time"],
                "unique_together": {("transcript", "word")},
            },
        ),
    ]
