# Generated by Django 6.0.1 on 2026-03-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0011_suggested_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedword",
            name="translation",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
