# Generated by Django 6.0.1 on 2026-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0012_suggested_word_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewsession",
            name="best_combo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewsession",
            name="score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reviewsession",
            name="session_type",
            field=models.CharField(
                choices=[
                    ("cloze", "Fill in the Blank"),
                    ("shadow", "Shadow Mode"),
                    ("review", "Quote Review"),
                    ("quiz", "Multiple Choice Quiz"),
                    ("mixed", "Mixed"),
                ],
                default="mixed",
                max_length=20,
            ),
        ),
    ]
