# Generated by Django 6.0.1 on 2026-03-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0013_session_score_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedword",
            name="level",
            field=models.CharField(
                choices=[("beginner", "Beginner"), ("intermediate", "Intermediate"), ("advanced", "Advanced")],
                default="beginner",
                max_length=15,
            ),
        ),
    ]
