# Generated by Django 6.0.1 on 2026-03-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_suggested_word_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedword",
            name="grammar_note",
            field=models.CharField(
                blank=True, default="", help_text='e.g. "awful (adj) → awfully (adv)"', max_length=300
            ),
        ),
        migrations.AddField(
            model_name="suggestedword",
            name="usage_examples",
            field=models.JSONField(
                blank=True, default=list, help_text='[{"en":"That\'s awful","uz":"Bu dahshatli"},...]'
            ),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="grammar_note",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="usage_examples",
            field=models.JSONField(blank=True, default=list, help_text='[{"en":"...","uz":"..."},...]'),
        ),
    ]
