# Generated by Django 6.0.1 on 2026-03-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0015_usage_grammar_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="suggestedword",
            name="definition",
            field=models.CharField(blank=True, default="", help_text="Short English definition", max_length=300),
        ),
        migrations.AddField(
            model_name="suggestedword",
            name="frequency",
            field=models.PositiveIntegerField(
                default=0, help_text="How many times this word appears across the entire show"
            ),
        ),
    ]
