# Generated by Django 6.0.1 on 2026-03-12 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0016_add_frequency_definition"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("english", models.TextField(help_text="Full English dialogue line")),
                ("translation", models.TextField(help_text="Full Uzbek translation of the line")),
                (
                    "accents",
                    models.JSONField(
                        default=list, help_text='Key vocab: [{"word":"come on","translation":"qo\'ysang-chi"}, ...]'
                    ),
                ),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learn_lines",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="learn_lines", to="clips.source"
                    ),
                ),
                (
                    "transcript",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="learn_line", to="clips.transcript"
                    ),
                ),
            ],
            options={
                "ordering": ["source", "season", "episode_number", "transcript__start_time"],
            },
        ),
    ]
