# Generated by Django 6.0.1 on 2026-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0017_add_learn_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(db_index=True, max_length=100, unique=True)),
                ("translation", models.CharField(max_length=300)),
                (
                    "level",
                    models.CharField(
                        choices=[("A1", "A1"), ("A2", "A2"), ("B1", "B1"), ("B2", "B2"), ("C1", "C1"), ("C2", "C2")],
                        default="B1",
                        max_length=2,
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=0, help_text="Frequency in the show")),
            ],
            options={
                "ordering": ["-frequency", "word"],
            },
        ),
    ]
