# Generated by Django 6.0.1 on 2026-03-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0018_add_word_translation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation", models.TextField(help_text="Uzbek translation of the dialogue line")),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_translations",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_translations",
                        to="clips.source",
                    ),
                ),
                (
                    "transcript",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_translation",
                        to="clips.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["source", "season", "episode_number", "transcript__start_time"],
            },
        ),
        migrations.CreateModel(
            name="LineVocab",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("english", models.CharField(help_text="The word or phrase in English", max_length=200)),
                ("translation", models.CharField(help_text="Uzbek translation", max_length=300)),
                ("context", models.TextField(blank=True, help_text="Pattern, usage note, or context explanation")),
                (
                    "kind",
                    models.CharField(
                        choices=[("phrase", "Phrase"), ("idiom", "Idiom"), ("word", "Word")],
                        default="word",
                        max_length=10,
                    ),
                ),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_vocab",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="line_vocab", to="clips.source"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="line_vocab", to="clips.transcript"
                    ),
                ),
            ],
            options={
                "ordering": ["source", "season", "episode_number", "transcript__start_time"],
                "unique_together": {("transcript", "english")},
            },
        ),
        migrations.DeleteModel(
            name="LearnLine",
        ),
    ]
