# Generated by Django 6.0.1 on 2026-03-15 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0019_replace_learnline_with_linetranslation_linevocab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[("flash", "Flash Match"), ("cloze", "Cloze"), ("produce", "Define & Use")],
                        max_length=10,
                    ),
                ),
                ("correct", models.BooleanField()),
                ("user_answer", models.CharField(blank=True, max_length=300)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="learning.linevocab",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VocabMastery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_score", models.FloatField(default=0, help_text="Flash Match score")),
                ("context_score", models.FloatField(default=0, help_text="Cloze score")),
                ("production_score", models.FloatField(default=0, help_text="Define & Use score")),
                ("overall_score", models.FloatField(default=0)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("shaky", "Shaky"),
                            ("good", "Good"),
                            ("strong", "Strong"),
                            ("mastered", "Mastered"),
                        ],
                        default="weak",
                        max_length=10,
                    ),
                ),
                ("streak", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_review", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocab_masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="masteries", to="learning.linevocab"
                    ),
                ),
            ],
            options={
                "ordering": ["overall_score"],
                "unique_together": {("user", "vocab")},
            },
        ),
    ]
