# Generated by Django 6.0.1 on 2026-03-16 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0020_add_vocabmastery_quizattempt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vocabmastery",
            options={"ordering": ["mastery_score"]},
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="chosen_wrong",
            field=models.CharField(
                blank=True, help_text="The wrong option user picked (for confusion detection)", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="direction",
            field=models.CharField(
                choices=[("l2_l1", "English → Uzbek"), ("l1_l2", "Uzbek → English")], default="l2_l1", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="learning.wordnote",
            ),
        ),
        migrations.AddField(
            model_name="vocabmastery",
            name="difficulty",
            field=models.FloatField(default=1000, help_text="Elo difficulty rating"),
        ),
        migrations.AddField(
            model_name="vocabmastery",
            name="mastery_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="vocabmastery",
            name="p_known",
            field=models.FloatField(default=0.1, help_text="P(L) — Bayesian knowledge probability"),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("flash", "Flash Match"),
                    ("cloze", "Cloze"),
                    ("produce", "Define & Use"),
                    ("match", "Match"),
                    ("listen", "Listen"),
                    ("teach", "Teach"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="vocab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="learning.linevocab",
            ),
        ),
        migrations.AlterField(
            model_name="vocabmastery",
            name="context_score",
            field=models.FloatField(default=0, help_text="P(L) for Cloze dimension"),
        ),
        migrations.AlterField(
            model_name="vocabmastery",
            name="production_score",
            field=models.FloatField(default=0, help_text="P(L) for Produce dimension"),
        ),
        migrations.AlterField(
            model_name="vocabmastery",
            name="translation_score",
            field=models.FloatField(default=0, help_text="P(L) for Flash/Match/Listen dimension"),
        ),
        migrations.CreateModel(
            name="UserLearningProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ability_rating", models.FloatField(default=1000)),
                ("weakness_phrasal_verb", models.FloatField(default=0.0)),
                ("weakness_idiom", models.FloatField(default=0.0)),
                ("weakness_single_word", models.FloatField(default=0.0)),
                ("weakness_abstract", models.FloatField(default=0.0)),
                ("weakness_phrase", models.FloatField(default=0.0)),
                ("words_known", models.PositiveIntegerField(default=0, help_text="Count of words with P(L)>0.5")),
                ("learning_rate", models.FloatField(default=0.0, help_text="Words learned per day (7-day avg)")),
                (
                    "retention_rate",
                    models.FloatField(default=0.0, help_text="Fraction of learned words retained after 7 days"),
                ),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("total_correct", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfusionPair",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word_a", models.CharField(help_text="The word being quizzed", max_length=200)),
                ("word_b", models.CharField(help_text="The word user confuses it with", max_length=200)),
                ("confusion_count", models.PositiveIntegerField(default=1)),
                ("last_confused", models.DateTimeField(auto_now=True)),
                ("resolved", models.BooleanField(default=False, help_text="True once user can distinguish them")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confusion_pairs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-confusion_count"],
                "unique_together": {("user", "word_a", "word_b")},
            },
        ),
    ]
