# Generated by Django 6.0.1 on 2026-03-16 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0021_bkt_mastery_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentencePattern",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("patterns", models.JSONField(default=list, help_text="List of detected pattern IDs")),
                ("text", models.TextField()),
                ("translation", models.TextField(blank=True)),
                (
                    "complexity_score",
                    models.FloatField(default=0, help_text="Weighted sum of pattern weights × clause multiplier"),
                ),
                ("difficulty_level", models.PositiveIntegerField(default=1, help_text="1-8 difficulty bracket")),
                ("clause_count", models.PositiveIntegerField(default=1)),
                ("primary_pattern", models.CharField(blank=True, db_index=True, max_length=30)),
                ("season", models.PositiveIntegerField(blank=True, null=True)),
                ("episode_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_patterns",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_patterns",
                        to="clips.source",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_patterns",
                        to="clips.transcript",
                    ),
                ),
            ],
            options={
                "ordering": ["complexity_score"],
                "unique_together": {("transcript", "primary_pattern")},
            },
        ),
        migrations.CreateModel(
            name="BuildAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pattern_tested", models.CharField(help_text="Which pattern was the focus", max_length=30)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("combine", "Clause Combiner"),
                            ("upgrade", "Sentence Upgrade"),
                            ("arrange", "Pattern Arrange"),
                        ],
                        max_length=10,
                    ),
                ),
                ("correct", models.BooleanField()),
                ("user_answer", models.TextField(blank=True)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sentence_pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="learning.sentencepattern",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatternMastery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "pattern",
                    models.CharField(db_index=True, help_text="Pattern ID from GRAMMAR_PATTERNS", max_length=30),
                ),
                ("p_known", models.FloatField(default=0.1, help_text="P(L) — Bayesian knowledge probability")),
                ("mastery_score", models.FloatField(default=0)),
                ("stars", models.PositiveIntegerField(default=0)),
                ("unlocked", models.BooleanField(default=False)),
                ("streak", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("last_played", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern_masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pattern"],
                "unique_together": {("user", "pattern")},
            },
        ),
    ]
