# Generated by Django 6.0.1 on 2026-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0023_add_grammar_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingsession",
            name="phrases_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="buildattempt",
            name="game_type",
            field=models.CharField(
                choices=[
                    ("meaning", "Meaning Match"),
                    ("fix", "Fix the Sentence"),
                    ("connect", "Pick Connector"),
                    ("complete", "Type Connector"),
                ],
                max_length=10,
            ),
        ),
    ]
