# Generated by Django 6.0.1 on 2026-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0024_add_phrases_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="description",
            field=models.TextField(blank=True, help_text="Clear meaning of the word or phrase"),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="example",
            field=models.TextField(blank=True, help_text="Example sentences showing usage"),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="pattern",
            field=models.CharField(
                blank=True, help_text="Grammar pattern formula, e.g. Find yourself + [-ing]", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="linevocab",
            name="context",
            field=models.TextField(blank=True, help_text="Legacy field — use description/example/pattern instead"),
        ),
        migrations.AlterField(
            model_name="linevocab",
            name="kind",
            field=models.CharField(
                choices=[
                    ("verb", "Verb"),
                    ("noun", "Noun"),
                    ("adj", "Adjective"),
                    ("adv", "Adverb"),
                    ("phrasal_verb", "Phrasal Verb"),
                    ("phrase", "Phrase"),
                    ("pattern", "Pattern"),
                    ("idiom", "Idiom"),
                ],
                default="phrase",
                max_length=15,
            ),
        ),
    ]
