# Generated by Django 6.0.1 on 2026-03-24 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0025_expand_linevocab_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linevocab",
            name="context",
        ),
    ]
