# Generated by Django 6.0.1 on 2026-03-25 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0026_remove_linevocab_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("watch_minutes", models.FloatField(default=0, help_text="Cumulative minutes spent watching video")),
                ("words_saved", models.PositiveIntegerField(default=0)),
                ("words_reviewed", models.PositiveIntegerField(default=0)),
                ("quiz_attempts", models.PositiveIntegerField(default=0)),
                ("quiz_correct", models.PositiveIntegerField(default=0)),
                ("build_attempts", models.PositiveIntegerField(default=0)),
                ("build_correct", models.PositiveIntegerField(default=0)),
                ("shadow_sessions", models.PositiveIntegerField(default=0)),
                ("shadow_loops", models.PositiveIntegerField(default=0)),
                ("shadow_minutes", models.FloatField(default=0)),
                ("grammar_attempts", models.PositiveIntegerField(default=0)),
                ("grammar_correct", models.PositiveIntegerField(default=0)),
                ("session_count", models.PositiveIntegerField(default=0)),
                ("total_minutes", models.FloatField(default=0, help_text="Total active learning minutes")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["user", "date"], name="learning_da_user_id_3cc234_idx")],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="GrammarPracticeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_id", models.PositiveIntegerField(help_text="Grammar unit number (1-8)")),
                ("unit_title", models.CharField(max_length=100)),
                ("sentence_index", models.PositiveIntegerField(help_text="Which sentence in the unit (0-based)")),
                ("sentence_text", models.TextField(help_text="The target sentence")),
                ("correct", models.BooleanField()),
                (
                    "attempts_on_sentence",
                    models.PositiveIntegerField(default=1, help_text="How many tries before getting it right"),
                ),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grammar_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "unit_id"], name="learning_gr_user_id_69d089_idx"),
                    models.Index(fields=["user", "created_at"], name="learning_gr_user_id_4c72de_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShadowingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phases_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="How many of the 4 phases completed (0=started only, 4=all done)"
                    ),
                ),
                (
                    "total_loops",
                    models.PositiveIntegerField(default=0, help_text="Total loop iterations across all phases"),
                ),
                (
                    "max_speed",
                    models.FloatField(default=0.5, help_text="Highest playback speed reached (0.5 / 0.75 / 1.0)"),
                ),
                (
                    "reached_no_subs",
                    models.BooleanField(
                        default=False, help_text="True if student reached the final no-subtitles phase"
                    ),
                ),
                (
                    "duration_sec",
                    models.PositiveIntegerField(default=0, help_text="Wall-clock seconds spent in shadowing mode"),
                ),
                ("line_text", models.TextField(blank=True, help_text="The transcript line text (cached)")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowing_logs",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="shadowing_logs", to="clips.source"
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowing_logs",
                        to="clips.transcript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadowing_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="learning_sh_user_id_893c87_idx"),
                    models.Index(fields=["user", "transcript"], name="learning_sh_user_id_12031d_idx"),
                ],
            },
        ),
    ]
