# Generated by Django 6.0.1 on 2026-03-25 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0027_add_shadowing_grammar_daily_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivity",
            name="flashcard_known",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="flashcard_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="lookups",
            field=models.PositiveIntegerField(default=0, help_text="Dictionary + translation lookups"),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="page_visits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FlashcardAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(help_text="Cached word text", max_length=200)),
                ("knew_it", models.BooleanField(help_text="True if user marked 'I know this'")),
                (
                    "time_on_card_ms",
                    models.PositiveIntegerField(default=0, help_text="Milliseconds spent on this card"),
                ),
                ("flips", models.PositiveIntegerField(default=1, help_text="How many times the card was flipped")),
                ("batch_date", models.DateField(help_text="Which day's batch this belongs to")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_attempts",
                        to="learning.wordnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "batch_date"], name="learning_fl_user_id_c2bc1c_idx"),
                    models.Index(fields=["user", "word_note"], name="learning_fl_user_id_2d2815_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LookupLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("word", models.CharField(max_length=200)),
                (
                    "lookup_type",
                    models.CharField(
                        choices=[("dictionary", "Dictionary"), ("translate", "Translation")], max_length=12
                    ),
                ),
                ("context", models.TextField(blank=True, help_text="Sentence context if available")),
                ("result_found", models.BooleanField(default=True, help_text="Whether a result was returned")),
                (
                    "saved_to_notebook",
                    models.BooleanField(default=False, help_text="Did user save this word after lookup?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_logs",
                        to="clips.episode",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lookup_logs",
                        to="clips.source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lookup_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "created_at"], name="learning_lo_user_id_2ed84a_idx"),
                    models.Index(fields=["user", "word"], name="learning_lo_user_id_6cd8ac_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "page",
                    models.CharField(help_text="Page identifier (e.g. 'quiz', 'watch', 'notebook')", max_length=100),
                ),
                ("path", models.CharField(help_text="Full URL path", max_length=500)),
                (
                    "duration_sec",
                    models.PositiveIntegerField(default=0, help_text="Seconds spent on page (updated on leave)"),
                ),
                ("referrer_page", models.CharField(blank=True, help_text="Which page user came from", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_visits",
                        to="clips.source",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "page"], name="learning_pa_user_id_1012f2_idx"),
                    models.Index(fields=["user", "created_at"], name="learning_pa_user_id_732c24_idx"),
                ],
            },
        ),
    ]
