# Generated by Django 6.0.1 on 2026-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0028_add_lookuplog_flashcardattempt_pagevisit_daily_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("social", "Social"),
                    ("relationships", "Relationships"),
                    ("emotions", "Emotions"),
                    ("home", "Home"),
                    ("body", "Body"),
                    ("food", "Food"),
                    ("humor", "Humor"),
                    ("personal_growth", "Personal Growth"),
                    ("general", "General"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("A1", "A1"), ("A2", "A2"), ("B1", "B1"), ("B2", "B2"), ("C1", "C1"), ("C2", "C2")],
                default="",
                max_length=2,
            ),
        ),
    ]
