# Generated by Django 6.0.1 on 2026-04-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0029_add_level_category_to_linevocab"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabmastery",
            name="ease_factor",
            field=models.FloatField(default=2.5, help_text="SM-2 ease factor (min 1.3)"),
        ),
        migrations.AddField(
            model_name="vocabmastery",
            name="interval_days",
            field=models.FloatField(default=0, help_text="Current SM-2 review interval in days"),
        ),
        migrations.AddField(
            model_name="vocabmastery",
            name="lapses",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times word lapsed (forgot after learning)"
            ),
        ),
    ]
