# Generated by Django 6.0.1 on 2026-04-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0030_add_sm2_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="vocab_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="FK to big_mastery.yaml id, e.g. 'go_through'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="linevocab",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("social", "Social"),
                    ("relationships", "Relationships"),
                    ("emotions", "Emotions"),
                    ("home", "Home"),
                    ("household", "Household"),
                    ("body", "Body"),
                    ("food", "Food"),
                    ("humor", "Humor"),
                    ("entertainment", "Entertainment"),
                    ("work", "Work"),
                    ("personal_growth", "Personal Growth"),
                    ("general", "General"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
