# Generated by Django 6.0.1 on 2026-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0031_add_vocab_id_to_linevocab"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="smart_mcq",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Scenario-based MCQ: {scenario, option_a, option_b, option_c, correct, feedback_uz}",
            ),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="tavsif",
            field=models.TextField(blank=True, help_text="Uzbek analogy/metaphor explaining the concept"),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="usage_check",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Spot-the-wrong: {sentence_1, sentence_2, sentence_3, wrong, reasoning_uz}",
            ),
        ),
    ]
