# Generated by Django 6.0.1 on 2026-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0032_add_tavsif_smart_mcq_usage_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="translated_examples",
            field=models.JSONField(
                blank=True, default=list, help_text="Paired UZ/EN sentences for retranslation: [{en, uz}, ...]"
            ),
        ),
    ]
