# Generated by Django 6.0.1 on 2026-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0033_linevocab_translated_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivity",
            name="words_mastered",
            field=models.PositiveIntegerField(default=0, help_text="Words that leveled up today"),
        ),
        migrations.AddField(
            model_name="dailyactivity",
            name="xp_earned",
            field=models.PositiveIntegerField(default=0, help_text="XP earned this day (drives goal ring)"),
        ),
    ]
