# Generated by Django 6.0.1 on 2026-04-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0034_dailyactivity_words_mastered_dailyactivity_xp_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="linevocab",
            name="collocations",
            field=models.JSONField(
                blank=True, default=list, help_text="Common natural collocations: ['go through a phase', ...]"
            ),
        ),
        migrations.AddField(
            model_name="linevocab",
            name="confusable_with",
            field=models.JSONField(blank=True, default=list, help_text="IDs of words learners confuse this with"),
        ),
    ]
