# Generated by Django 6.0.1 on 2026-04-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0035_add_confusable_collocations"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="scene_frame",
            field=models.ImageField(
                blank=True, help_text="Video screenshot from the moment of save", null=True, upload_to="scene_frames/"
            ),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="scene_timestamp",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Video time (seconds) when the word was saved",
                max_digits=10,
                null=True,
            ),
        ),
    ]
