# Generated by Django 6.0.1 on 2026-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0036_add_scene_frame"),
    ]

    operations = [
        migrations.AddField(
            model_name="wordnote",
            name="last_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="next_review",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="When this word should be reviewed next (SRS schedule)", null=True
            ),
        ),
        migrations.AddField(
            model_name="wordnote",
            name="review_count",
            field=models.PositiveIntegerField(default=0, help_text="Times this word completed a Challenge session"),
        ),
    ]
