# Generated by Django 6.0.1 on 2026-04-22 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0037_wordnote_last_reviewed_at_wordnote_next_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("football", "Football"),
                            ("music", "Music"),
                            ("movies", "Movies & TV"),
                            ("food", "Food"),
                            ("gaming", "Gaming"),
                            ("travel", "Travel"),
                            ("tech", "Technology"),
                            ("books", "Books"),
                            ("fashion", "Fashion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        blank=True, default=list, help_text='[{"label":"Barcelona","source":"preset"}, ...]'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
                "unique_together": {("user", "category")},
            },
        ),
    ]
