# Generated by Django 6.0.1 on 2026-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0038_add_user_interest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinterest",
            name="category",
            field=models.CharField(
                choices=[
                    ("forever_movie", "Forever Movie"),
                    ("football", "Football"),
                    ("music", "Music"),
                    ("movies", "Movies & TV"),
                    ("food", "Food"),
                    ("gaming", "Gaming"),
                    ("travel", "Travel"),
                    ("tech", "Technology"),
                    ("books", "Books"),
                    ("fashion", "Fashion"),
                ],
                max_length=20,
            ),
        ),
    ]
