# Generated by Django 6.0.1 on 2026-04-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0039_add_forever_movie_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarAIExplanation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unit_id", models.PositiveSmallIntegerField()),
                (
                    "question_index",
                    models.PositiveIntegerField(
                        help_text="Zero-based index into the unit's question pool in grammar_questions.json"
                    ),
                ),
                (
                    "chosen_option",
                    models.PositiveSmallIntegerField(help_text="Index of the wrong option the learner picked"),
                ),
                (
                    "explanation_uz",
                    models.TextField(help_text="Gemini-generated explanation in Uzbek (Latin script), 1-3 sentences"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hit_count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "indexes": [models.Index(fields=["unit_id", "question_index"], name="learning_gr_unit_id_cfe322_idx")],
                "unique_together": {("unit_id", "question_index", "chosen_option")},
            },
        ),
    ]
