# Generated by Django 6.0.1 on 2026-05-02 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0040_grammaraiexplanation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSentence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "word",
                    models.CharField(
                        blank=True, default="", help_text="The target word/phrase the learner used", max_length=120
                    ),
                ),
                (
                    "uzbek_prompt",
                    models.TextField(blank=True, default="", help_text="The Uzbek prompt the learner translated from"),
                ),
                (
                    "english",
                    models.TextField(
                        help_text="The English the learner produced — the artifact we replay back to them"
                    ),
                ),
                ("quiz_type", models.CharField(default="mastered_bridge", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_sentences",
                        to="learning.wordnote",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_sentences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["user", "-created_at"], name="learning_sa_user_id_1b8e74_idx")],
            },
        ),
    ]
