# Generated by Django 6.0.1 on 2026-05-02 18:09
# Plus a backfill data step that hydrates pre-fix NULL next_review rows
# to NOW so they actually enter the review cycle. Pre-fix, 92% of saved
# words had next_review=NULL and were silently skipped.

import django.utils.timezone
from django.db import migrations, models


def backfill_next_review(apps, schema_editor):
    """Set next_review = now for any WordNote where it's still NULL.

    Reverse-safe (the inverse data op is a no-op — once you've reviewed
    a word you don't want to nuke its schedule on rollback)."""
    WordNote = apps.get_model("learning", "WordNote")
    from django.utils import timezone

    WordNote.objects.filter(next_review__isnull=True).update(
        next_review=timezone.now(),
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0041_add_saved_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordnote",
            name="next_review",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=django.utils.timezone.now,
                help_text="When this word should be reviewed next (SRS schedule)",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_next_review, noop_reverse),
    ]
