# Generated by Django 6.0.1 on 2026-05-02 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0042_fix_next_review_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SceneCoverage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_tokens", models.IntegerField(default=0)),
                ("known_tokens", models.IntegerField(default=0)),
                ("coverage", models.FloatField(default=0.0)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="coverages", to="clips.transcript"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scene_coverages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "-coverage"], name="learning_sc_user_id_65d6e4_idx"),
                    models.Index(fields=["user", "transcript"], name="learning_sc_user_id_e1cef0_idx"),
                ],
                "unique_together": {("user", "transcript")},
            },
        ),
    ]
