# Generated by Django 6.0.1 on 2026-05-07 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_sceneblock"),
        ("learning", "0043_add_scene_coverage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonemeWeakness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phoneme", models.CharField(max_length=20)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("fails", models.PositiveIntegerField(default=0, help_text="Times this phoneme scored < 60")),
                ("avg_accuracy", models.FloatField(default=0)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phoneme_weaknesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["user", "-fails"], name="learning_ph_user_id_a2c481_idx")],
                "unique_together": {("user", "phoneme")},
            },
        ),
        migrations.CreateModel(
            name="PronunciationAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("audio_file", models.FileField(blank=True, null=True, upload_to="pronunciation/%Y/%m/")),
                ("audio_duration_ms", models.PositiveIntegerField(default=0)),
                ("accuracy_score", models.FloatField(default=0, help_text="Phoneme-level pronunciation accuracy")),
                ("fluency_score", models.FloatField(default=0, help_text="Smoothness / pacing")),
                ("completeness_score", models.FloatField(default=0, help_text="Did the user say all the words?")),
                (
                    "prosody_score",
                    models.FloatField(blank=True, help_text="Rhythm/stress (Azure prosody, optional)", null=True),
                ),
                (
                    "overall_score",
                    models.FloatField(default=0, help_text="Composite score, what the UI surfaces as headline"),
                ),
                ("word_scores", models.JSONField(blank=True, default=list)),
                ("weak_phonemes", models.JSONField(blank=True, default=list)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shadow_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Shadow session this assessment belongs to (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="learning.shadowinglog",
                    ),
                ),
                (
                    "transcript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_assessments",
                        to="clips.transcript",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pronunciation_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="learning_pr_user_id_0f70f4_idx"),
                    models.Index(fields=["user", "transcript"], name="learning_pr_user_id_bec28f_idx"),
                ],
            },
        ),
    ]
