# Generated by Django 6.0.1 on 2026-05-12 12:55
# Wrapped in SeparateDatabaseAndState — removes vocab models from learning ORM state only.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0045_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="CoreWord",
                ),
                migrations.RemoveField(
                    model_name="linetranslation",
                    name="episode",
                ),
                migrations.RemoveField(
                    model_name="linetranslation",
                    name="source",
                ),
                migrations.RemoveField(
                    model_name="linetranslation",
                    name="transcript",
                ),
                migrations.AlterUniqueTogether(
                    name="linevocab",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="linevocab",
                    name="episode",
                ),
                migrations.RemoveField(
                    model_name="linevocab",
                    name="source",
                ),
                migrations.RemoveField(
                    model_name="linevocab",
                    name="transcript",
                ),
                migrations.RemoveField(
                    model_name="vocabmastery",
                    name="vocab",
                ),
                migrations.AlterUniqueTogether(
                    name="suggestedword",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="suggestedword",
                    name="episode",
                ),
                migrations.RemoveField(
                    model_name="suggestedword",
                    name="source",
                ),
                migrations.RemoveField(
                    model_name="suggestedword",
                    name="transcript",
                ),
                migrations.AlterUniqueTogether(
                    name="vocabmastery",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="vocabmastery",
                    name="user",
                ),
            ],
            database_operations=[],
        ),
    ]
