# Generated by Django 6.0.1 on 2026-05-12 12:55
# Wrapped in SeparateDatabaseAndState — deletes remaining vocab models from learning ORM state only.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0046_initial"),
        ("quiz", "0002_initial"),
        ("vocab", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="onboardingresult",
                    name="word",
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vocab.vocabword"),
                ),
                migrations.DeleteModel(
                    name="WordCache",
                ),
                migrations.AlterUniqueTogether(
                    name="wordnote",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="wordnote",
                    name="quote",
                ),
                migrations.RemoveField(
                    model_name="wordnote",
                    name="transcript",
                ),
                migrations.RemoveField(
                    model_name="wordnote",
                    name="user",
                ),
                migrations.AlterField(
                    model_name="flashcardattempt",
                    name="word_note",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_attempts",
                        to="vocab.wordnote",
                    ),
                ),
                migrations.DeleteModel(
                    name="WordTranslation",
                ),
                migrations.DeleteModel(
                    name="LineTranslation",
                ),
                migrations.DeleteModel(
                    name="LineVocab",
                ),
                migrations.DeleteModel(
                    name="SuggestedWord",
                ),
                migrations.DeleteModel(
                    name="VocabMastery",
                ),
                migrations.DeleteModel(
                    name="VocabWord",
                ),
                migrations.DeleteModel(
                    name="WordNote",
                ),
            ],
            database_operations=[],
        ),
    ]
