"""
Filter word_list.csv and generate batched translation files for ChatGPT.

Removes: SKIP_WORDS, freq > 500, short words, proper names.
Outputs: media/translation/batch_01.txt, batch_02.txt, etc. (500 words each)

Usage:
    python scripts/batch_translate.py
"""

import re
from pathlib import Path

BATCH_SIZE = 500

# Copy of SKIP_WORDS from extract_vocab.py
SKIP_WORDS = {
    "i",
    "you",
    "he",
    "she",
    "we",
    "they",
    "it",
    "me",
    "my",
    "your",
    "his",
    "her",
    "our",
    "their",
    "its",
    "us",
    "him",
    "them",
    "myself",
    "yourself",
    "himself",
    "herself",
    "themselves",
    "ourselves",
    "the",
    "a",
    "an",
    "this",
    "that",
    "these",
    "those",
    "and",
    "but",
    "or",
    "if",
    "so",
    "than",
    "because",
    "since",
    "until",
    "while",
    "although",
    "unless",
    "whether",
    "in",
    "on",
    "at",
    "to",
    "for",
    "with",
    "about",
    "from",
    "of",
    "by",
    "up",
    "out",
    "off",
    "down",
    "over",
    "under",
    "after",
    "before",
    "between",
    "into",
    "through",
    "around",
    "without",
    "during",
    "against",
    "what",
    "who",
    "how",
    "where",
    "when",
    "why",
    "which",
    "whose",
    "can",
    "will",
    "would",
    "could",
    "should",
    "may",
    "might",
    "must",
    "shall",
    "be",
    "is",
    "am",
    "are",
    "was",
    "were",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "done",
    "doing",
    "go",
    "goes",
    "went",
    "gone",
    "going",
    "get",
    "got",
    "gets",
    "getting",
    "say",
    "said",
    "says",
    "saying",
    "make",
    "made",
    "makes",
    "making",
    "know",
    "knew",
    "known",
    "knows",
    "think",
    "thought",
    "thinks",
    "come",
    "came",
    "comes",
    "coming",
    "see",
    "saw",
    "seen",
    "sees",
    "look",
    "looked",
    "looking",
    "looks",
    "want",
    "wanted",
    "wants",
    "give",
    "gave",
    "gives",
    "given",
    "take",
    "took",
    "taken",
    "takes",
    "tell",
    "told",
    "tells",
    "find",
    "found",
    "finds",
    "put",
    "puts",
    "putting",
    "try",
    "tried",
    "tries",
    "trying",
    "leave",
    "left",
    "leaves",
    "call",
    "called",
    "calls",
    "keep",
    "kept",
    "keeps",
    "let",
    "lets",
    "need",
    "needed",
    "needs",
    "feel",
    "felt",
    "feels",
    "mean",
    "meant",
    "means",
    "ask",
    "asked",
    "asks",
    "seem",
    "seemed",
    "seems",
    "help",
    "helped",
    "helps",
    "talk",
    "talked",
    "talks",
    "turn",
    "turned",
    "turns",
    "start",
    "started",
    "starts",
    "show",
    "showed",
    "shown",
    "hear",
    "heard",
    "hears",
    "move",
    "moved",
    "moves",
    "live",
    "lived",
    "lives",
    "believe",
    "believed",
    "happen",
    "happened",
    "happens",
    "work",
    "worked",
    "works",
    "hold",
    "held",
    "bring",
    "brought",
    "sit",
    "sat",
    "stand",
    "stood",
    "set",
    "catch",
    "caught",
    "sophisticate",
    "good",
    "bad",
    "great",
    "big",
    "little",
    "small",
    "long",
    "short",
    "new",
    "old",
    "young",
    "right",
    "wrong",
    "nice",
    "happy",
    "ready",
    "best",
    "better",
    "worse",
    "worst",
    "hard",
    "easy",
    "fine",
    "free",
    "sure",
    "true",
    "real",
    "whole",
    "different",
    "same",
    "only",
    "just",
    "really",
    "very",
    "well",
    "too",
    "also",
    "still",
    "even",
    "never",
    "always",
    "maybe",
    "already",
    "again",
    "actually",
    "probably",
    "ever",
    "yet",
    "almost",
    "enough",
    "quite",
    "pretty",
    "here",
    "there",
    "now",
    "then",
    "today",
    "tonight",
    "tomorrow",
    "much",
    "more",
    "most",
    "many",
    "few",
    "less",
    "some",
    "any",
    "every",
    "each",
    "another",
    "other",
    "both",
    "all",
    "no",
    "not",
    "yes",
    "yeah",
    "ok",
    "okay",
    "alright",
    "man",
    "woman",
    "people",
    "guy",
    "guys",
    "life",
    "time",
    "day",
    "night",
    "morning",
    "year",
    "thing",
    "things",
    "way",
    "place",
    "world",
    "home",
    "house",
    "room",
    "door",
    "water",
    "food",
    "money",
    "phone",
    "car",
    "name",
    "mother",
    "father",
    "brother",
    "sister",
    "friend",
    "baby",
    "boy",
    "girl",
    "hand",
    "head",
    "face",
    "eyes",
    "job",
    "school",
    "number",
    "lot",
    "kind",
    "part",
    "everybody",
    "everyone",
    "someone",
    "something",
    "nothing",
    "anything",
    "question",
    "answer",
    "problem",
    "gonna",
    "gotta",
    "wanna",
    "kinda",
    "oh",
    "hey",
    "hi",
    "hello",
    "bye",
    "please",
    "thank",
    "thanks",
    "sorry",
    "wow",
    "god",
    "ah",
    "uh",
    "um",
    "er",
    "hmm",
    "mmm",
    "la",
    "ooh",
    "low",
    "high",
    "close",
    "open",
    "full",
    "late",
    "early",
    "fast",
    "slow",
    "loud",
    "quiet",
    "deep",
    "wide",
    "flat",
    "hot",
    "cold",
    "warm",
    "cool",
    "dark",
    "light",
    "clear",
    "clean",
    "dirty",
    "dry",
    "wet",
    "soft",
    "strong",
    "weak",
    "rich",
    "poor",
    "thick",
    "thin",
    "heavy",
    "tight",
    "loose",
    "sharp",
    "bright",
    "rough",
    "smooth",
    "safe",
    "dead",
    "alive",
    "hers",
    "his",
    "theirs",
    "ours",
    "mine",
    "yours",
    "use",
    "used",
    "using",
    "uses",
    "run",
    "ran",
    "running",
    "runs",
    "play",
    "played",
    "playing",
    "read",
    "write",
    "wrote",
    "open",
    "opened",
    "close",
    "closed",
    "stop",
    "stopped",
    "stops",
    "send",
    "sent",
    "pay",
    "paid",
    "spend",
    "spent",
    "win",
    "won",
    "lose",
    "lost",
    "cut",
    "tie",
    "tied",
    "tying",
    "wait",
    "waited",
    "pick",
    "picked",
    "pass",
    "passed",
    "wear",
    "wore",
    "worn",
    "carry",
    "carried",
    "change",
    "changed",
    "watch",
    "watched",
    "follow",
    "followed",
    "lead",
    "led",
    "grow",
    "grew",
    "grown",
    "draw",
    "drew",
    "drawn",
    "break",
    "broke",
    "broken",
    "first",
    "last",
    "next",
    "second",
    "third",
    "fourth",
    "fifth",
    "else",
    "anyway",
    "back",
    "away",
    "ago",
    "own",
    "together",
    "half",
    "course",
    "mostly",
    "especially",
    "sometimes",
    "sometime",
    "don",
    "didn",
    "doesn",
    "won",
    "isn",
    "wasn",
    "weren",
    "hasn",
    "haven",
    "wouldn",
    "couldn",
    "shouldn",
    "re",
    "ve",
    "ll",
    "s",
    "t",
    "d",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
}

# Friends character names and common proper nouns to skip
NAMES = {
    "ross",
    "rachel",
    "rach",
    "monica",
    "chandler",
    "joey",
    "phoebe",
    "carol",
    "barry",
    "carl",
    "brandy",
    "geppetto",
    "joni",
    "chachi",
    "liza",
    "minnelli",
    "david",
    "joan",
    "pinocchio",
    "billy",
    "tony",
    "dimarco",
    "limoges",
    "rachael",
    "vegas",
    "lincoln",
    "florida",
    "aruba",
    "ruba",
    "charles",
    "paul",
    "wee",
    "las",
    "ben",
    "frank",
    "janice",
    "richard",
    "emily",
    "mike",
    "jack",
    "judy",
    "susan",
    "pete",
    "tag",
    "mona",
    "parker",
    "gavin",
    "elizabeth",
    "charlie",
    "erica",
    "jill",
    "amy",
    "ursula",
    "gunther",
    "mr",
    "mrs",
    "ms",
    "dr",
    "st",
    "jr",
}


def main():
    # Read word_list.csv
    words = []
    with open("word_list.csv") as f:
        for line in f:
            parts = line.strip().split(",")
            if len(parts) == 2:
                word, freq = parts[0].strip(), int(parts[1])
                words.append((word, freq))

    # Filter
    filtered = []
    for word, freq in words:
        wl = word.lower()
        # Skip ultra-common (freq > 500)
        if freq > 500:
            continue
        # Skip words in SKIP_WORDS
        if wl in SKIP_WORDS:
            continue
        # Skip names
        if wl in NAMES:
            continue
        # Skip too short
        if len(wl) <= 2:
            continue
        # Skip contractions and fragments
        if "'" in wl or not re.match(r"^[a-z]+$", wl):
            continue
        filtered.append((word, freq))

    print(f"Total in word_list.csv: {len(words)}")
    print(f"After filtering: {len(filtered)}")

    # Sort by frequency (high to low) so most useful words come first
    filtered.sort(key=lambda x: -x[1])

    # Generate batch files
    out_dir = Path("media/translation/batches")
    out_dir.mkdir(parents=True, exist_ok=True)

    num_batches = (len(filtered) + BATCH_SIZE - 1) // BATCH_SIZE
    for i in range(num_batches):
        batch = filtered[i * BATCH_SIZE : (i + 1) * BATCH_SIZE]
        batch_num = i + 1
        out_file = out_dir / f"batch_{batch_num:02d}.txt"

        with open(out_file, "w") as f:
            f.write(f"Translate these English words to Uzbek. Format: word | Uzbek translation\n")
            f.write(
                f"Keep translations short (1-3 words). If a word has multiple meanings, give the most common one.\n\n"
            )
            for word, freq in batch:
                f.write(f"{word}\n")

        print(f"  Batch {batch_num}: {len(batch)} words → {out_file}")

    print(f"\nTotal batches: {num_batches}")
    print(f"Copy each batch file content to ChatGPT and ask it to translate.")


if __name__ == "__main__":
    main()
