"""
Walk through all Transcript lines and extract medium-level vocabulary
(single words AND common phrases).

Usage:
    poetry run python -m core.manage extract_suggestions
    poetry run python -m core.manage extract_suggestions --source 1
    poetry run python -m core.manage extract_suggestions --out suggestions.json
"""

import json
import re
from collections import defaultdict
from pathlib import Path

from django.core.management.base import BaseCommand

from clips.models import Transcript

# ═══════════════════════════════════════════════════════════════════════
# SKIP LIST — top ~2500 most common English words + all forms
# These are too easy for intermediate learners.
# ═══════════════════════════════════════════════════════════════════════
COMMON_WORDS = {
    # ── Function words (articles, pronouns, prepositions, conjunctions) ──
    "a",
    "an",
    "the",
    "i",
    "me",
    "my",
    "mine",
    "we",
    "us",
    "our",
    "ours",
    "you",
    "your",
    "yours",
    "he",
    "him",
    "his",
    "she",
    "her",
    "hers",
    "it",
    "its",
    "they",
    "them",
    "their",
    "theirs",
    "this",
    "that",
    "these",
    "those",
    "who",
    "whom",
    "which",
    "what",
    "whose",
    "where",
    "when",
    "why",
    "how",
    "all",
    "each",
    "every",
    "both",
    "few",
    "more",
    "most",
    "other",
    "others",
    "some",
    "such",
    "no",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "just",
    "but",
    "and",
    "or",
    "nor",
    "if",
    "then",
    "else",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "into",
    "here",
    "there",
    "once",
    "twice",
    "also",
    "always",
    "never",
    "now",
    "already",
    "still",
    "even",
    "anyway",
    "maybe",
    "really",
    "right",
    "well",
    "back",
    "away",
    "around",
    "however",
    "yet",
    "please",
    "yes",
    "yeah",
    "yep",
    "nope",
    "okay",
    "ok",
    "sure",
    "alright",
    # ── Reflexive / demonstrative ──
    "myself",
    "yourself",
    "himself",
    "herself",
    "itself",
    "ourselves",
    "themselves",
    "nothing",
    "something",
    "everything",
    "anything",
    "someone",
    "everyone",
    "anyone",
    "nobody",
    "somebody",
    "everybody",
    "anybody",
    "somewhere",
    "anywhere",
    "nowhere",
    "everywhere",
    # ── Numbers & time ──
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "hundred",
    "thousand",
    "million",
    "half",
    "second",
    "third",
    "first",
    "last",
    "next",
    "ago",
    "soon",
    "tonight",
    "tomorrow",
    "yesterday",
    "forever",
    "today",
    "morning",
    "afternoon",
    "evening",
    "night",
    "week",
    "weeks",
    "month",
    "months",
    "year",
    "years",
    "minute",
    "minutes",
    "hour",
    "hours",
    "times",
    "since",
    "already",
    # ── Common verbs (base + all forms) ──
    "be",
    "am",
    "is",
    "are",
    "was",
    "were",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "done",
    "say",
    "said",
    "says",
    "saying",
    "go",
    "goes",
    "went",
    "gone",
    "going",
    "get",
    "gets",
    "got",
    "gotten",
    "getting",
    "make",
    "makes",
    "made",
    "making",
    "know",
    "knows",
    "knew",
    "known",
    "knowing",
    "think",
    "thinks",
    "thought",
    "thinking",
    "take",
    "takes",
    "took",
    "taken",
    "taking",
    "come",
    "comes",
    "came",
    "coming",
    "see",
    "sees",
    "saw",
    "seen",
    "seeing",
    "want",
    "wants",
    "wanted",
    "wanting",
    "look",
    "looks",
    "looked",
    "looking",
    "use",
    "uses",
    "used",
    "using",
    "find",
    "finds",
    "found",
    "finding",
    "give",
    "gives",
    "gave",
    "given",
    "giving",
    "tell",
    "tells",
    "told",
    "telling",
    "work",
    "works",
    "worked",
    "working",
    "call",
    "calls",
    "called",
    "calling",
    "try",
    "tries",
    "tried",
    "trying",
    "ask",
    "asks",
    "asked",
    "asking",
    "need",
    "needs",
    "needed",
    "needing",
    "feel",
    "feels",
    "felt",
    "feeling",
    "leave",
    "leaves",
    "left",
    "leaving",
    "put",
    "puts",
    "putting",
    "mean",
    "means",
    "meant",
    "meaning",
    "keep",
    "keeps",
    "kept",
    "keeping",
    "let",
    "lets",
    "letting",
    "begin",
    "begins",
    "began",
    "begun",
    "show",
    "shows",
    "showed",
    "shown",
    "showing",
    "hear",
    "hears",
    "heard",
    "hearing",
    "play",
    "plays",
    "played",
    "playing",
    "run",
    "runs",
    "ran",
    "running",
    "move",
    "moves",
    "moved",
    "moving",
    "like",
    "likes",
    "liked",
    "liking",
    "live",
    "lives",
    "lived",
    "living",
    "believe",
    "believes",
    "believed",
    "hold",
    "holds",
    "held",
    "holding",
    "bring",
    "brings",
    "brought",
    "bringing",
    "happen",
    "happens",
    "happened",
    "happening",
    "write",
    "writes",
    "wrote",
    "written",
    "writing",
    "sit",
    "sits",
    "sat",
    "sitting",
    "stand",
    "stands",
    "stood",
    "standing",
    "lose",
    "loses",
    "lost",
    "losing",
    "pay",
    "pays",
    "paid",
    "paying",
    "meet",
    "meets",
    "met",
    "meeting",
    "set",
    "sets",
    "setting",
    "learn",
    "learns",
    "learned",
    "learning",
    "change",
    "changes",
    "changed",
    "changing",
    "lead",
    "leads",
    "led",
    "leading",
    "understand",
    "understands",
    "understood",
    "watch",
    "watches",
    "watched",
    "watching",
    "follow",
    "follows",
    "followed",
    "following",
    "stop",
    "stops",
    "stopped",
    "stopping",
    "speak",
    "speaks",
    "spoke",
    "spoken",
    "speaking",
    "read",
    "reads",
    "reading",
    "spend",
    "spends",
    "spent",
    "spending",
    "grow",
    "grows",
    "grew",
    "grown",
    "growing",
    "open",
    "opens",
    "opened",
    "opening",
    "walk",
    "walks",
    "walked",
    "walking",
    "win",
    "wins",
    "won",
    "winning",
    "teach",
    "teaches",
    "taught",
    "teaching",
    "buy",
    "buys",
    "bought",
    "buying",
    "wait",
    "waits",
    "waited",
    "waiting",
    "die",
    "dies",
    "died",
    "dying",
    "dead",
    "send",
    "sends",
    "sent",
    "sending",
    "build",
    "builds",
    "built",
    "building",
    "fall",
    "falls",
    "fell",
    "fallen",
    "falling",
    "cut",
    "cuts",
    "cutting",
    "reach",
    "reaches",
    "reached",
    "reaching",
    "kill",
    "kills",
    "killed",
    "killing",
    "stay",
    "stays",
    "stayed",
    "staying",
    "talk",
    "talks",
    "talked",
    "talking",
    "love",
    "loves",
    "loved",
    "loving",
    "hate",
    "hates",
    "hated",
    "hating",
    "eat",
    "eats",
    "ate",
    "eaten",
    "eating",
    "drink",
    "drinks",
    "drank",
    "drunk",
    "drinking",
    "sleep",
    "sleeps",
    "slept",
    "sleeping",
    "drive",
    "drives",
    "drove",
    "driven",
    "driving",
    "break",
    "breaks",
    "broke",
    "broken",
    "breaking",
    "wear",
    "wears",
    "wore",
    "worn",
    "wearing",
    "start",
    "starts",
    "started",
    "starting",
    "help",
    "helps",
    "helped",
    "helping",
    "close",
    "closes",
    "closed",
    "closing",
    "turn",
    "turns",
    "turned",
    "turning",
    "pull",
    "pulls",
    "pulled",
    "pulling",
    "push",
    "pushes",
    "pushed",
    "pushing",
    "pick",
    "picks",
    "picked",
    "picking",
    "carry",
    "carries",
    "carried",
    "carrying",
    "offer",
    "offers",
    "offered",
    "offering",
    "remember",
    "remembers",
    "remembered",
    "remembering",
    "consider",
    "considers",
    "considered",
    "appear",
    "appears",
    "appeared",
    "appearing",
    "expect",
    "expects",
    "expected",
    "expecting",
    "suggest",
    "suggests",
    "suggested",
    "drop",
    "drops",
    "dropped",
    "dropping",
    "raise",
    "raises",
    "raised",
    "raising",
    "pass",
    "passes",
    "passed",
    "passing",
    "sell",
    "sells",
    "sold",
    "selling",
    "decide",
    "decides",
    "decided",
    "deciding",
    "return",
    "returns",
    "returned",
    "returning",
    "explain",
    "explains",
    "explained",
    "explaining",
    "hope",
    "hopes",
    "hoped",
    "hoping",
    "miss",
    "misses",
    "missed",
    "missing",
    "care",
    "cares",
    "cared",
    "caring",
    "figure",
    "figures",
    "figured",
    "guess",
    "guesses",
    "guessed",
    "catch",
    "catches",
    "caught",
    "throw",
    "throws",
    "threw",
    "thrown",
    "dance",
    "dances",
    "danced",
    "dancing",
    "answer",
    "answers",
    "answered",
    "share",
    "shares",
    "shared",
    "deal",
    "deals",
    "dealt",
    "wish",
    "wishes",
    "wished",
    "invite",
    "invites",
    "invited",
    "hang",
    "hangs",
    "hung",
    "kiss",
    "kisses",
    "kissed",
    "marry",
    "marries",
    "married",
    "worry",
    "worries",
    "worried",
    "relax",
    "relaxes",
    "relaxed",
    "forget",
    "forgets",
    "forgot",
    "forgotten",
    "seem",
    "seems",
    "seemed",
    "touch",
    "touches",
    "touched",
    "save",
    "saves",
    "saved",
    "fight",
    "fights",
    "fought",
    "suppose",
    "supposes",
    "supposed",
    "check",
    "checks",
    "checked",
    "clean",
    "cleans",
    "cleaned",
    "sign",
    "signs",
    "signed",
    # ── Common nouns (expanded) ──
    "time",
    "people",
    "way",
    "day",
    "days",
    "man",
    "men",
    "woman",
    "women",
    "child",
    "children",
    "world",
    "life",
    "hand",
    "hands",
    "part",
    "place",
    "case",
    "company",
    "system",
    "question",
    "work",
    "thing",
    "things",
    "school",
    "state",
    "family",
    "group",
    "country",
    "problem",
    "problems",
    "city",
    "name",
    "team",
    "eye",
    "eyes",
    "room",
    "home",
    "water",
    "mother",
    "area",
    "money",
    "story",
    "fact",
    "lot",
    "book",
    "job",
    "word",
    "words",
    "side",
    "head",
    "house",
    "door",
    "car",
    "cars",
    "food",
    "body",
    "dog",
    "girl",
    "girls",
    "boy",
    "boys",
    "guy",
    "guys",
    "friend",
    "friends",
    "father",
    "power",
    "hour",
    "game",
    "line",
    "end",
    "law",
    "face",
    "night",
    "point",
    "idea",
    "number",
    "phone",
    "table",
    "bed",
    "baby",
    "wife",
    "husband",
    "brother",
    "sister",
    "son",
    "daughter",
    "street",
    "road",
    "town",
    "party",
    "picture",
    "music",
    "movie",
    "movies",
    "office",
    "class",
    "teacher",
    "doctor",
    "paper",
    "letter",
    "sir",
    "moment",
    "person",
    "heart",
    "hair",
    "mind",
    "couple",
    "date",
    "coffee",
    "dinner",
    "lunch",
    "apartment",
    "store",
    "hospital",
    "parents",
    "keys",
    "card",
    "cards",
    "dollar",
    "dollars",
    "floor",
    "stuff",
    "course",
    "matter",
    "kind",
    "sort",
    "type",
    "shoe",
    "shoes",
    "foot",
    "feet",
    "finger",
    "fingers",
    "boyfriend",
    "girlfriend",
    "bathroom",
    "bedroom",
    "kitchen",
    "kids",
    "wine",
    "beer",
    "dress",
    "shirt",
    "ring",
    "machine",
    "doctor",
    "nurse",
    "boss",
    "age",
    "business",
    "plan",
    "plans",
    "trouble",
    "bunch",
    "rest",
    "sex",
    "joke",
    "jokes",
    # ── Common adjectives (expanded) ──
    "good",
    "great",
    "big",
    "small",
    "little",
    "long",
    "new",
    "old",
    "young",
    "high",
    "low",
    "large",
    "real",
    "important",
    "different",
    "bad",
    "happy",
    "true",
    "nice",
    "best",
    "better",
    "worse",
    "worst",
    "whole",
    "possible",
    "late",
    "hard",
    "early",
    "wrong",
    "ready",
    "sorry",
    "fine",
    "funny",
    "pretty",
    "cute",
    "beautiful",
    "cool",
    "sweet",
    "perfect",
    "hot",
    "cold",
    "sick",
    "crazy",
    "stupid",
    "free",
    "full",
    "special",
    "easy",
    "clear",
    "enough",
    "able",
    "single",
    "white",
    "black",
    "red",
    "blue",
    "green",
    "dark",
    "angry",
    "alone",
    "upset",
    "weird",
    "scared",
    "amazing",
    "weird",
    "terrible",
    "awful",
    "serious",
    "naked",
    "boring",
    "another",
    "certain",
    "entire",
    "strong",
    "huge",
    # ── Common adverbs & misc ──
    "much",
    "many",
    "any",
    "bit",
    "quite",
    "rather",
    "almost",
    "together",
    "probably",
    "certainly",
    "actually",
    "exactly",
    "definitely",
    "especially",
    "absolutely",
    "totally",
    "completely",
    "basically",
    "apparently",
    "obviously",
    "honestly",
    "seriously",
    "literally",
    "anymore",
    "anymore",
    "whatever",
    "whenever",
    "unless",
    "except",
    "without",
    "instead",
    "either",
    "neither",
    "sometimes",
    "though",
    "several",
    "along",
    "behind",
    "upon",
    "across",
    "towards",
    "less",
    "least",
    # ── Interjections & filler ──
    "whoa",
    "ahem",
    "ooh",
    "ohh",
    "umm",
    "hmm",
    "huh",
    "ugh",
    "aww",
    "eww",
    "yay",
    "woah",
    "shh",
    "psst",
    "argh",
    "phew",
    "geez",
    "gee",
    "duh",
    "blah",
    "meh",
    "nah",
    "hello",
    "listen",
    "look",
    "welcome",
    "thank",
    "thanks",
    "goodbye",
    "excuse",
    "gonna",
    "gotta",
    "wanna",
    "kinda",
    "lotta",
    "alrighty",
    "hell",
    "damn",
    "crap",
    "god",
    "dear",
    "honey",
    "sweetie",
    # Still too common for intermediate
    "ever",
    "might",
    "shall",
    "must",
    "could",
    "would",
    "should",
    "sound",
    "sounds",
    "sounded",
    "shut",
    "cannot",
    "although",
    "ended",
    "finished",
    "hurt",
    "hurts",
    "lights",
    "light",
    "aunt",
    "uncle",
    "grandma",
    "grandpa",
    "dream",
    "dreams",
    "dreamed",
    "birthday",
    "christmas",
    "halloween",
    "kidding",
    # Character nicknames
    "rach",
    "pheebs",
    "mon",
}

# ═══════════════════════════════════════════════════════════════════════
# COMMON PHRASES worth extracting as units
# These are phrasal verbs, idioms, and expressions learners should
# know as a whole — not as individual words.
# ═══════════════════════════════════════════════════════════════════════
PHRASE_PATTERNS = [
    # Phrasal verbs
    r"\b(figure[sd]? out)\b",
    r"\b(find[s]? out|found out)\b",
    r"\b(turn[sed]* out)\b",
    r"\b(turn[sed]* down)\b",
    r"\b(turn[sed]* up)\b",
    r"\b(give[sn]* up|gave up)\b",
    r"\b(give[s]* back|gave back)\b",
    r"\b(come[s]* up with|came up with)\b",
    r"\b(go[es]* through|went through|gone through)\b",
    r"\b(go[es]* out with|went out with|gone out with)\b",
    r"\b(get[s]* over|got over|gotten over)\b",
    r"\b(get[s]* rid of|got rid of|gotten rid of)\b",
    r"\b(get[s]* along|got along|gotten along)\b",
    r"\b(pick[sed]* up)\b",
    r"\b(break[s]* up|broke up|broken up)\b",
    r"\b(make[s]* up|made up)\b",
    r"\b(make[s]* out|made out)\b",
    r"\b(make[s]* fun of|made fun of)\b",
    r"\b(run[s]* into|ran into)\b",
    r"\b(end[sed]* up)\b",
    r"\b(set[s]* up)\b",
    r"\b(show[sed]* up|shown up)\b",
    r"\b(work[sed]* out)\b",
    r"\b(put[s]* up with)\b",
    r"\b(look[sed]* forward to)\b",
    r"\b(look[sed]* up)\b",
    r"\b(look[sed]* into)\b",
    r"\b(take[s]* care of|took care of|taken care of)\b",
    r"\b(take[s]* off|took off|taken off)\b",
    r"\b(take[s]* over|took over|taken over)\b",
    r"\b(hang[s]* out|hung out)\b",
    r"\b(hang[s]* up|hung up)\b",
    r"\b(check[sed]* out)\b",
    r"\b(pass[sed]* out)\b",
    r"\b(freak[sed]* out)\b",
    r"\b(kick[sed]* out)\b",
    r"\b(blow[sn]* off|blew off)\b",
    r"\b(screw[sed]* up)\b",
    r"\b(calm[sed]* down)\b",
    r"\b(settle[sd]? down)\b",
    r"\b(shut[s]* up)\b",
    r"\b(mess[sed]* up)\b",
    r"\b(bring[s]* up|brought up)\b",
    r"\b(point[sed]* out)\b",
    # Idioms & expressions
    r"\b(a big deal)\b",
    r"\b(no wonder)\b",
    r"\b(on purpose)\b",
    r"\b(for good)\b",
    r"\b(in charge)\b",
    r"\b(in case)\b",
    r"\b(no big deal)\b",
    r"\b(how come)\b",
    r"\b(in common)\b",
    r"\b(on my own)\b",
    r"\b(on your own)\b",
    r"\b(so far)\b",
    r"\b(by the way)\b",
    r"\b(what if)\b",
]

MIN_WORD_LEN = 4
MAX_LINE_FREQUENCY = 40
MIN_LINE_FREQUENCY = 2


def clean_text(text):
    """Remove speaker tags, stage directions, and artifacts."""
    text = re.sub(r"\b[A-Z]{2,}:", "", text)  # ROSS:
    text = re.sub(r"\[.*?\]", "", text)  # [laughs]
    text = re.sub(r"\(.*?\)", "", text)  # (sighs)
    text = re.sub(r"''", '"', text)  # '' → "
    return text.strip()


def tokenize(text):
    """Extract clean words — no possessives, no contractions, no fragments."""
    text = clean_text(text)
    # Remove possessives: Monica's → Monica, it's stays as contraction
    text = re.sub(r"(\w)'s\b", r"\1", text)
    # Remove other contractions entirely (don't, wouldn't, etc.)
    text = re.sub(r"\w+'[a-z]+", "", text)
    # Extract only alphabetic words
    words = re.findall(r"\b[a-z]{2,}\b", text.lower())
    return words


class Command(BaseCommand):
    help = "Extract medium-level vocabulary from transcripts into a JSON file"

    def add_arguments(self, parser):
        parser.add_argument("--source", type=int, help="Source ID to scan (default: all)")
        parser.add_argument("--out", type=str, default="suggestions.json", help="Output JSON file path")

    def handle(self, *args, **options):
        source_id = options.get("source")
        out_path = options["out"]

        qs = Transcript.objects.select_related("source", "episode")
        if source_id:
            qs = qs.filter(source_id=source_id)

        transcripts = list(qs.order_by("source", "episode", "start_time"))
        self.stdout.write(f"Scanning {len(transcripts)} transcript lines...")

        # ════════════════════════════════════════════════════
        # Phase 1: Extract PHRASES from transcript lines
        # ════════════════════════════════════════════════════
        phrase_lines = defaultdict(list)

        for t in transcripts:
            cleaned = clean_text(t.text).lower()
            for pattern in PHRASE_PATTERNS:
                match = re.search(pattern, cleaned, re.IGNORECASE)
                if match:
                    phrase = match.group(1).lower().strip()
                    phrase_lines[phrase].append(t)

        # ════════════════════════════════════════════════════
        # Phase 2: Extract single WORDS
        # ════════════════════════════════════════════════════
        word_lines = defaultdict(list)

        for t in transcripts:
            words_in_line = set(tokenize(t.text))
            for w in words_in_line:
                if len(w) >= MIN_WORD_LEN and w not in COMMON_WORDS:
                    word_lines[w].append(t)

        # ════════════════════════════════════════════════════
        # Phase 3: Filter — medium frequency, skip names
        # ════════════════════════════════════════════════════
        suggestions = []

        # Process phrases first
        for phrase, lines in sorted(phrase_lines.items(), key=lambda x: -len(x[1])):
            count = len(lines)
            if count < MIN_LINE_FREQUENCY:
                continue
            best = max(lines, key=lambda t: len(t.text))
            suggestions.append(self._build_entry(phrase, best, count, lines, is_phrase=True))

        self.stdout.write(f"  {len(suggestions)} phrases extracted")

        # Process single words
        word_count = 0
        for word, lines in sorted(word_lines.items(), key=lambda x: -len(x[1])):
            count = len(lines)
            if count < MIN_LINE_FREQUENCY or count > MAX_LINE_FREQUENCY:
                continue

            # Skip probable names (capitalized >60% of time, not at sentence start)
            cap = 0
            sample = lines[:10]
            for line in sample:
                tokens = re.findall(r"\b\w+", line.text)
                for i, tok in enumerate(tokens):
                    if tok.lower() == word and i > 0 and tok[0].isupper():
                        cap += 1
                        break
            if sample and cap / len(sample) > 0.6:
                continue

            best = max(lines, key=lambda t: len(t.text))
            suggestions.append(self._build_entry(word, best, count, lines, is_phrase=False))
            word_count += 1

        self.stdout.write(f"  {word_count} words extracted")

        # Sort: phrases first, then by frequency
        suggestions.sort(key=lambda x: (-x.get("is_phrase", False), -x["occurrences"]))

        # ════════════════════════════════════════════════════
        # Phase 4: Translate all words to Uzbek
        # ════════════════════════════════════════════════════
        self.stdout.write(f"\nTranslating {len(suggestions)} words...")
        import time

        from deep_translator import GoogleTranslator

        translator = GoogleTranslator(source="en", target="uz")

        for i, entry in enumerate(suggestions):
            try:
                # Translate a short phrase around the word for context-aware results
                # e.g. "shot" alone → "otish" (shooting), but "give it a shot" → correct meaning
                snippet = self._extract_snippet(entry["word"], entry["sentence"])
                entry["translation"] = translator.translate(snippet)
            except Exception:
                try:
                    entry["translation"] = translator.translate(entry["word"])
                except Exception:
                    entry["translation"] = ""
            if (i + 1) % 50 == 0:
                self.stdout.write(f"  {i + 1}/{len(suggestions)} translated")
                time.sleep(0.5)  # small pause every 50 to avoid rate limits

        self.stdout.write(f"  {len(suggestions)}/{len(suggestions)} done")

        out_file = Path(out_path)
        out_file.write_text(json.dumps(suggestions, indent=2, ensure_ascii=False))
        self.stdout.write(self.style.SUCCESS(f"\nWrote {len(suggestions)} suggestions to {out_file.resolve()}"))

    def _build_entry(self, word, best_line, count, all_lines, is_phrase=False):
        t = best_line
        source = t.source
        episode = t.episode

        entry = {
            "word": word,
            "is_phrase": is_phrase,
            "sentence": t.text,
            "source_id": source.id if source else None,
            "source_title": source.title if source else "",
            "source_type": source.source_type if source else "",
            "transcript_id": t.id,
            "start_time": str(t.start_time),
            "end_time": str(t.end_time),
            "occurrences": count,
        }

        if episode:
            entry["episode_id"] = episode.id
            entry["season"] = episode.season
            entry["episode_number"] = episode.episode_number
            entry["episode_title"] = episode.title
        else:
            entry["episode_id"] = None
            entry["season"] = None
            entry["episode_number"] = None
            entry["episode_title"] = None

        examples = []
        for ex in all_lines[:3]:
            examples.append(
                {
                    "text": ex.text,
                    "start_time": str(ex.start_time),
                    "end_time": str(ex.end_time),
                    "episode_id": ex.episode_id,
                }
            )
        entry["examples"] = examples

        return entry

    def _extract_snippet(self, word, sentence):
        """
        Extract a short 3-5 word phrase around the target word from the sentence.
        Translating a short phrase gives much better context than the word alone.
        e.g. "shot" alone → "otish" (shooting), but "give it a shot" → "sinab ko'rish"
        """
        # Clean the sentence
        clean = re.sub(r"[A-Z]+:", "", sentence).strip()  # remove speaker tags
        words_list = clean.split()
        lower_words = [w.lower().strip(".,!?'\"()-") for w in words_list]

        # Find the word position
        target = word.lower()
        idx = -1
        if " " in target:
            # Phrase — find the first word of the phrase
            first_word = target.split()[0]
            for i, w in enumerate(lower_words):
                if w == first_word:
                    idx = i
                    break
        else:
            for i, w in enumerate(lower_words):
                if w == target:
                    idx = i
                    break

        if idx == -1:
            return word  # fallback to just the word

        # Take 2 words before and 2 after for context
        start = max(0, idx - 2)
        end = min(len(words_list), idx + len(target.split()) + 2)
        snippet = " ".join(words_list[start:end])

        # Clean up snippet edges
        snippet = snippet.strip(".,!?'\"()-")
        return snippet if snippet else word
